"""Curated cancer gene reference panel.

Roles and relevance notes are based on well-established cancer biology
(COSMIC Cancer Gene Census / OncoKB consensus classifications). This is
not exhaustive -- it is a deliberately small, high-confidence panel.
"""

BIOMARKER_PANEL = {
    "TP53": {"role": "tumor_suppressor", "relevance": "Most frequently mutated gene in human cancer; guards genome integrity via cell-cycle arrest and apoptosis."},
    "EGFR": {"role": "oncogene", "relevance": "Receptor tyrosine kinase driving proliferation; activating mutations/amplification common in lung cancer and glioblastoma."},
    "KRAS": {"role": "oncogene", "relevance": "GTPase central to RAS/MAPK signaling; among the most commonly mutated oncogenes in pancreatic, colorectal, and lung cancer."},
    "MYC": {"role": "oncogene", "relevance": "Master transcription factor driving proliferation and metabolism; amplified or dysregulated across many cancer types."},
    "BRCA1": {"role": "tumor_suppressor", "relevance": "DNA double-strand break repair via homologous recombination; germline mutations confer hereditary breast/ovarian cancer risk."},
    "BRCA2": {"role": "tumor_suppressor", "relevance": "Partners with BRCA1/RAD51 in homologous recombination repair; germline mutations confer hereditary breast/ovarian cancer risk."},
    "PTEN": {"role": "tumor_suppressor", "relevance": "Phosphatase that antagonizes PI3K/AKT signaling; loss drives proliferation and survival in many solid tumors."},
    "RB1": {"role": "tumor_suppressor", "relevance": "Controls G1/S cell-cycle checkpoint; inactivation is the founding lesion in retinoblastoma and common in many cancers."},
    "PIK3CA": {"role": "oncogene", "relevance": "Catalytic subunit of PI3K; activating mutations drive AKT/mTOR signaling in breast and other solid tumors."},
    "ERBB2": {"role": "oncogene", "relevance": "Also known as HER2; receptor tyrosine kinase amplified in a clinically actionable subset of breast and gastric cancers."},
    "ALK": {"role": "oncogene", "relevance": "Receptor tyrosine kinase; fusion events (e.g., EML4-ALK) are targetable drivers in non-small cell lung cancer."},
    "MET": {"role": "proto-oncogene", "relevance": "Hepatocyte growth factor receptor; amplification/mutation drives proliferation and invasion, targetable in NSCLC."},
    "VEGFA": {"role": "oncogene", "relevance": "Key driver of tumor angiogenesis; overexpression supports blood supply to growing tumors and is a therapeutic target."},
    "MDM2": {"role": "oncogene", "relevance": "Negative regulator of p53 via ubiquitination; amplification inactivates p53 tumor suppression without TP53 mutation."},
    "CDKN2A": {"role": "tumor_suppressor", "relevance": "Encodes p16/p14ARF; regulates RB and p53 pathways, frequently deleted across many cancer types."},
    "APC": {"role": "tumor_suppressor", "relevance": "Negative regulator of Wnt/beta-catenin signaling; loss is the initiating event in most colorectal cancers."},
    "VHL": {"role": "tumor_suppressor", "relevance": "Targets HIF-alpha for degradation; loss causes constitutive hypoxia signaling, hallmark of clear cell renal carcinoma."},
    "NF1": {"role": "tumor_suppressor", "relevance": "RAS-GAP that negatively regulates RAS signaling; loss causes neurofibromatosis and predisposes to several tumor types."},
    "STK11": {"role": "tumor_suppressor", "relevance": "Also known as LKB1; regulates AMPK/mTOR energy sensing, mutated in Peutz-Jeghers syndrome and lung adenocarcinoma."},
    "SMAD4": {"role": "tumor_suppressor", "relevance": "Central mediator of TGF-beta signaling; loss is common in pancreatic and colorectal cancer."},
    "IDH1": {"role": "oncogene", "relevance": "Metabolic enzyme; hotspot mutations produce oncometabolite 2-HG, defining a glioma and AML subtype."},
    "IDH2": {"role": "oncogene", "relevance": "Mitochondrial paralog of IDH1; hotspot mutations produce 2-HG oncometabolite, notably in AML."},
    "BRAF": {"role": "oncogene", "relevance": "Serine/threonine kinase in MAPK pathway; V600E mutation is a targetable driver in melanoma and other cancers."},
    "NRAS": {"role": "oncogene", "relevance": "RAS family GTPase; activating mutations drive MAPK signaling in melanoma and hematologic malignancies."},
    "CTNNB1": {"role": "oncogene", "relevance": "Encodes beta-catenin; stabilizing mutations constitutively activate Wnt target gene transcription."},
    "ATM": {"role": "tumor_suppressor", "relevance": "Apical kinase of the DNA damage response; germline mutations cause ataxia-telangiectasia and cancer predisposition."},
    "CHEK2": {"role": "tumor_suppressor", "relevance": "Checkpoint kinase downstream of ATM; germline variants increase breast and other cancer risk."},
    "PALB2": {"role": "tumor_suppressor", "relevance": "Links BRCA1 and BRCA2 in homologous recombination repair; germline mutations confer breast cancer risk."},
    "MLH1": {"role": "tumor_suppressor", "relevance": "DNA mismatch repair gene; loss causes microsatellite instability and Lynch syndrome cancers."},
    "MSH2": {"role": "tumor_suppressor", "relevance": "DNA mismatch repair gene; loss causes microsatellite instability and Lynch syndrome cancers."},
    "MSH6": {"role": "tumor_suppressor", "relevance": "DNA mismatch repair gene; germline mutations associated with Lynch syndrome, particularly endometrial cancer."},
    "PMS2": {"role": "tumor_suppressor", "relevance": "DNA mismatch repair gene; loss contributes to microsatellite instability in Lynch syndrome cancers."},
    "FGFR1": {"role": "oncogene", "relevance": "Fibroblast growth factor receptor; amplification/fusion drives proliferation in lung, breast, and myeloid malignancies."},
    "FGFR2": {"role": "oncogene", "relevance": "Fibroblast growth factor receptor; activating alterations are targetable drivers in cholangiocarcinoma and gastric cancer."},
    "FGFR3": {"role": "oncogene", "relevance": "Fibroblast growth factor receptor; activating mutations/fusions drive bladder cancer and multiple myeloma."},
    "CCND1": {"role": "oncogene", "relevance": "Encodes cyclin D1; drives G1/S cell-cycle transition, frequently amplified in breast cancer and mantle cell lymphoma."},
    "CCNE1": {"role": "oncogene", "relevance": "Encodes cyclin E1; amplification drives replication stress and genomic instability in ovarian and gastric cancer."},
    "AKT1": {"role": "oncogene", "relevance": "Serine/threonine kinase downstream of PI3K; activating mutations promote survival and proliferation signaling."},
    "PDGFRA": {"role": "oncogene", "relevance": "Receptor tyrosine kinase; activating mutations drive gastrointestinal stromal tumors (GIST) and gliomas."},
    "KIT": {"role": "oncogene", "relevance": "Receptor tyrosine kinase; activating mutations are the primary driver in most gastrointestinal stromal tumors."},
    "RET": {"role": "oncogene", "relevance": "Receptor tyrosine kinase; fusions/mutations drive medullary thyroid carcinoma and a subset of NSCLC, both targetable."},
    "ROS1": {"role": "oncogene", "relevance": "Receptor tyrosine kinase; gene fusions define a targetable driver subset of non-small cell lung cancer."},
    "NTRK1": {"role": "oncogene", "relevance": "Neurotrophin receptor kinase; fusions are rare but highly actionable pan-cancer drivers with dedicated targeted therapy."},
    "JAK2": {"role": "oncogene", "relevance": "Cytokine receptor-associated kinase; V617F mutation is the primary driver of myeloproliferative neoplasms."},
    "NOTCH1": {"role": "oncogene", "relevance": "Cell-fate signaling receptor; activating mutations drive T-cell acute lymphoblastic leukemia."},
    "GATA3": {"role": "tumor_suppressor", "relevance": "Transcription factor controlling luminal mammary differentiation; frequently mutated in breast cancer."},
    "FOXA1": {"role": "oncogene", "relevance": "Pioneer transcription factor that cooperates with estrogen/androgen receptors; dysregulated in breast and prostate cancer."},
    "ESR1": {"role": "oncogene", "relevance": "Encodes estrogen receptor alpha; ligand-binding domain mutations drive endocrine therapy resistance in breast cancer."},
    "PGR": {"role": "proto-oncogene", "relevance": "Progesterone receptor; expression status guides breast cancer subtyping and endocrine therapy decisions."},
    "ERBB3": {"role": "proto-oncogene", "relevance": "Also known as HER3; heterodimerizes with HER2/EGFR to amplify growth signaling, implicated in therapy resistance."},
}
